### ISSUE TITLE
Fatal exception when constructing a GvrView

### ISSUE THREAD

**Issue by isometriq** [googlevr/gvr-android-sdk#264]
Since using gvr 1.0
`GvrView mView = new GvrView(context);`

will cause this:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.sphereplay.vrplayer, PID: 27515
                  java.lang.NoClassDefFoundError: com.google.vrtoolkit.cardboard.proto.nano.Phone$PhoneParams
                      at com.google.vr.cardboard.ConfigUtils.readPhoneParamsFromExternalStorage(SourceFile:124)
                      at com.google.vr.cardboard.LegacyVrParamsProvider.readPhoneParams(SourceFile:37)
                      at com.google.vr.sdk.base.HeadMountedDisplayManager.createScreenParams(HeadMountedDisplayManager.java:163)
                      at com.google.vr.sdk.base.HeadMountedDisplayManager.<init>(HeadMountedDisplayManager.java:53)
                      at com.google.vr.sdk.base.CardboardViewNativeImpl.<init>(CardboardViewNativeImpl.java:81)
                      at com.google.vr.sdk.base.ImplementationSelector.createCardboardViewApi(ImplementationSelector.java:34)
                      at com.google.vr.sdk.base.GvrView.init(GvrView.java:764)
                      at com.google.vr.sdk.base.GvrView.<init>(GvrView.java:242)
```

on a Samsung Galaxy Alpha, os 5.1
Any clues?

**Comment by isometriq** [comment]
Works with the files from tag 0.9.1

**Comment by sp-1234** [comment]
Same problem

**Comment by sigmaxipi** [comment]
Did you update your gradle files to pull in external dependencies? We unbundled our protobuf and exoplayer dependencies: https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/build.gradle

**Comment by isometriq** [comment]
Ok, I did not realized this had changed. I can see that also in the "get-started".

**Comment by isometriq** [comment]
It works now
